services:

  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
#      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--log.filePath=/logs/traefik.log" 
      - "--accesslog=true"
      - "--accesslog.filePath=/logs/access.log"
      # entrypoints definition
      - "--entryPoints.web.address=:80"
      - "--entryPoints.https.address=:443"
      # HTTPS
      - "--certificatesresolvers.certif.acme.httpchallenge=true"
    environment:
      - TZ=Europe/Paris
    ports:
      # HTTP Port
      - "80:80"
      # HTTPS Port
      - "443:443"
    volumes:
      # traefik listen to Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs/:/logs/"
      - "./letsencrypt:/letsencrypt"
    networks:
      - traefik-public
      - internal

networks:
  internal:
    name: internal
    driver: bridge
  traefik-public:
    name: traefik-public
    external: true