api:
  dashboard: false
  insecure: true

entryPoints:
  web:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: YOUR_EMAIL
      storage: "./letsencrypt/acme.json"          
      httpChallenge:
        entryPoint: web
  
log:
  level: DEBUG
