services:

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - internal

networks:
  internal:
    name: internal
    driver: bridge

volumes:
  grafana-storage: {}